### ISSUE TITLE
Video descripción del curso

### ISSUE THREAD

**Issue by ferney606** [bambuco/moodle-block_vitrina#1]
Al tratar de visualizar el video de la descripción del curso (Campo dinámico - Media)
no se visualiza el video, solo se queda en el recuadro negro. al visualizarlo dentro del inspector de código es como si se agregara código adicional

Moodle_ 4.1

Se visualiza lo siguiente:

<div class="media-content">
                        <video controls="controls">
                            <source src="<p dir=&quot;ltr&quot; style=&quot;text-align:left;&quot;><a href=&quot;https://www.youtube.com/embed/uiT3RnbOqmg&quot; class=&quot;_blanktarget&quot;>https://www.youtube.com/embed/uiT3RnbOqmg</a><br /></p>" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                </div>

al parecer en el source se crean tags adicionales

se puede comprobar el mensaje de error en este pantallazo

Muchas gracias
![error_video](https://user-images.githubusercontent.com/90972732/236315356-90044211-d347-406a-b818-eb23658f7626.png)

**Comment by davidherney** [comment]
No se pudo reproducir... por favor envía más información como la URL que guardaste e imágenes del campo donde lo configuraste en el curso.
Es probable que hayas copiando HTML adicional o que hayas usado un campo o filtro que esté transformando la URL en contenido HTML.

Revisa por favor.

Saludos

**Comment by ferney606** [comment]
cambié el campo de curso personalizado a texto corto y funcionó de una. 

Muchas gracias
